channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - nbgitpuller
  - jupyter-server-proxy
  - qgis
  - qgis-plugin-manager
  - awscli
  - libgdal-arrow-parquet
  - libgdal-netcdf
  - pip:
    - jupyter-remote-desktop-proxy
    - git+https://github.com/sunu/jupyter-remote-qgis-proxy@deb511ec7ece043c3a4e1b5fe31caf3f070e8a58
